name: 🐞 Bug Report
description: Report a bug in the app
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the bug clearly
    validations:
      required: true
