name: 🌟 Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      placeholder: What would you like to see?
    validations:
      required: true
